# Generated by Django 3.1.1 on 2020-09-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='youtube_recent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('publishedAt', models.CharField(max_length=100)),
                ('channelId', models.CharField(max_length=50)),
                ('categoryId', models.CharField(max_length=50)),
                ('trending_date', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=50)),
                ('view_count', models.CharField(max_length=50)),
                ('likes', models.CharField(max_length=10)),
                ('dislikes', models.CharField(max_length=10)),
                ('comment_count', models.CharField(max_length=10)),
                ('thumbnail_link', models.CharField(max_length=100)),
                ('comments_disabled', models.CharField(max_length=50)),
                ('ratings_disabled', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
