# Generated by Django 3.1.1 on 2020-09-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_youtube_recent'),
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('classification', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('topic_rate', models.CharField(max_length=50)),
            ],
        ),
    ]
